# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM --platform=$BUILDPLATFORM google-go.pkg.dev/golang:1.26.4@sha256:3444149d0a7e3f7cfb9c2db65f0f75676fe6ad04de3ce72674efb120c08dd1c1 AS driverbuilder

ARG TARGETARCH

WORKDIR /go/src/github.com/GoogleCloudPlatform/lustre-csi-driver
ADD . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} go build -mod vendor -ldflags "-s -w -extldflags '-static'" -o /bin/lustre-csi-driver cmd/csi_driver/main.go

FROM gke.gcr.io/debian-base:bookworm-v1.0.7-gke.2 AS debian
ENV DEBIAN_FRONTEND=noninteractive

RUN clean-install bash ca-certificates

FROM debian
COPY --from=driverbuilder /bin/lustre-csi-driver /lustre-csi-driver
ENTRYPOINT ["/lustre-csi-driver"]
